services:
  php:
    ports:
      - 8080:80
    container_name: php8.3
    volumes:
      - ./app:/var/www/app/
    build:
      context: .
      dockerfile: Dockerfile

  db:
    platform: linux/amd64
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - 3306
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - mysqlphpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST:mysql
      - MYSQL_ROOT_PASSWORD:admin
    networks:
      - mysqlphpmyadmin
    depends_on:
      - db

networks:
  mysqlphpmyadmin:

volumes:
  db_data:
