services:
  php:
    ports:
      - 8080:80
    container_name: php8.3
    volumes:
      - ./app:/var/www/app/
    build:
      context: .
      dockerfile: Dockerfile

  db:
    platform: linux/x86_64
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - mysqlphpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST:mysql
      - MYSQL_ROOT_PASSWORD:admin
    networks:
      - mysqlphpmyadmin
    depends_on:
      - db

networks:
  mysqlphpmyadmin:
    driver: bridge

volumes:
  db_data:
